services:
  db:
    container_name: postgres-restaurant
    image: postgres
    environment:
      POSTGRES_USER: restaurant
      POSTGRES_PASSWORD: password
      PGDTA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
